### ISSUE TITLE
[XML] Issue writing list of Elements

### ISSUE THREAD

**Issue by RUSshy** [Relfos/LunarParser#10]
Let's say i have: 

```XML

<data>
    <entry>
        <name>Test1</name>
        <desc>Test1</desc>
    </entry>
    <entry>
        <name>Test2</name>
        <desc>Test2</desc>
    </entry>
</data>
```

When using XMLWriter it transforms into:

```XML
<data>
    <entry name="Test1" desc="Test1" />
    <entry name="Test2" desc="Test2" />
</data>
```

Is there a way to not alter the original structure of the DataNode?

Looks like it makes no differenciation between Element/Attributes

**Comment by Relfos** [comment]
Thanks for the issue report, I've pushed now a change that improves this a bit, also updated the Nuget package.

Now when you call XMLWriter.WriteToString() theres a new optional parameter "expand". Pass true to that and you should obtain the expected result. 

However this is just a quick fix, might not work in all cases if you have something complex where you mix attributes and nodes. If you still find some place where it does not work please tell me

**Comment by RUSshy** [comment]
Thanks!
